config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root    'matches#index'
  # Users
  match   'users/new',              to: 'users#new',            via: %i[get post], as: 'new_user'

  # Sessions
  match   'login',                  to: 'sessions#new',         via: %i[get post], as: 'login'
  delete  'logout',                 to: 'sessions#destroy'

  # Profiles
  get     '/profile/edit',          to: 'profiles#edit'
  resource :profile,                only: %i[update]

  # Adventures
  post    '/adventures/search',     to: 'adventures#search'

  # Matches
  get     '/matches',               to: 'matches#index'
  post    '/matches/reject',        to: 'matches#reject'
  post    '/matches/accept',        to: 'matches#accept'

  # Chats
  resources :chats do
    post '/', to: 'chats#new_message'
    post '/retrieve', to: 'chats#retrieve'
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  validates_presence_of :email, :name
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, length: { minimum: 6 }

  has_one :profile, dependent: :destroy
  delegate :matches, :rejects, :accepts, :new_matches, to: :profile
  after_save :create_profile

  has_many :messages
  has_many :chats, -> { distinct }, through: :messages

  private

  def create_profile
    Profile.find_or_create_by!(user_id: id)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
    return unless request.post?

    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to profile_edit_path, notice: "Welcome to Wildfire, #{@user.name}"
    else
      render :new, status: :bad_request
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/views/users/new.html.erb
<div class="container-fluid row d-flex align-items-center">
  <div class="col-12 col-md-6">
    <%
        images = [
          "https://images.unsplash.com/photo-1473713984581-b8918cc3652e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80",
          "https://images.unsplash.com/photo-1494137319847-a9592a0e73ed?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=873&q=80",
          "https://images.unsplash.com/photo-1496521061024-90e1c1221555?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=871&q=80",
          "https://images.unsplash.com/photo-1517769160849-02feaecfd6cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80",
          "https://images.unsplash.com/photo-1572155935026-e6fbec6a2697?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80"
        ]
    %>
      <%= image_tag images.sample,
                    class: "img-fluid rounded",
                    alt: "Couple Sitting in Hammock" %>
  </div>
  <%= form_for @user, url: new_user_path, method: :post, html: { class: "d-block col-12 col-md-6" } do |form| %>
    <% if @user.errors.any? %>
      <% errors = @user.errors.full_messages.join(", ") %>
      <div class="alert alert-danger show position-absolute w-full top-0 end-0 m-5 w-full" role="alert">
        <%= errors %>
      </div>
    <% end %>
    <div class="form-group my-2">
      <%= form.text_field :name,
                          required: true,
                          placeholder: "Full Name",
                          class: "form-control form-control-sm" %>
    </div>
    <div class="form-group my-2">
      <%= form.email_field :email,
                           required: true,
                           placeholder: "Email Address",
                           class: "form-control form-control-sm" %>
    </div>
    <div class="form-group my-2">
      <%= form.password_field :password,
                              required: true,
                              placeholder: "Password",
                              class: "form-control form-control-sm" %>
    </div>
    <div class="form-group my-2">
      <%= form.password_field :password_confirmation,
                              required: true,
                              placeholder: "Confirm Password",
                              class: "form-control form-control-sm" %>
    </div>
    <div class="form-group my-2 text-end">
      <%= form.submit "Create an Account", class: "btn btn-sm btn-soft" %>
      <div class="mx-1 my-2 text-muted small">
        Already registered?&nbsp;<%= link_to "Login", login_path %>
      </div>
    </div>
  <% end %>
</div>