config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root    'matches#index'
  # Users
  match   'users/new',              to: 'users#new',            via: %i[get post], as: 'new_user'

  # Sessions
  match   'login',                  to: 'sessions#new',         via: %i[get post], as: 'login'
  delete  'logout',                 to: 'sessions#destroy'

  # Profiles
  get     '/profile/edit',          to: 'profiles#edit'
  resource :profile,                only: %i[update]

  # Adventures
  post    '/adventures/search',     to: 'adventures#search'

  # Matches
  get     '/matches',               to: 'matches#index'
  post    '/matches/reject',        to: 'matches#reject'
  post    '/matches/accept',        to: 'matches#accept'

  # Chats
  resources :chats do
    post '/', to: 'chats#new_message'
    post '/retrieve', to: 'chats#retrieve'
  end
end

app/views/shared/_flash.html.erb
<%
  klass = {
    alert: "danger",
    notice: "primary",
    success: "success"
  }
%>

<% flash.each do |type, msg| %>
  <div class="alert alert-<%= klass[type.to_sym] %> show position-absolute w-full top-0 end-0 m-5 w-full" role="alert">
    <%= raw msg %>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-transparent mx-auto w-full">
  <div class="justify-content-center mx-auto" id="navbarNavAltMarkup">
    <div class="navbar-nav flex-row">
      <a class="nav-item nav-link px-2 <%= "active" if current_page?(root_path) %>" href="<%= matches_path %>">Match</a>
      <a class="nav-item nav-link px-2 <%= "active" if current_page?(chats_path) %>" href="<%= chats_path %>">
        <%= content_tag :i, nil, class: "fa fa-exclamation-circle" if @current_user.new_matches %> Chats
      </a>
      <a class="nav-item nav-link px-2 <%= "active" if current_page?(profile_edit_path) %>" href="<%= profile_edit_path %>">My Profile</a>
      <%= button_to "Logout", logout_path, method: :delete, class: "nav-item nav-link px-2" %>
    </div>
  </div>
</nav>