config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root    'matches#index'
  # Users
  match   'users/new',              to: 'users#new',            via: %i[get post], as: 'new_user'

  # Sessions
  match   'login',                  to: 'sessions#new',         via: %i[get post], as: 'login'
  delete  'logout',                 to: 'sessions#destroy'

  # Profiles
  get     '/profile/edit',          to: 'profiles#edit'
  resource :profile,                only: %i[update]

  # Adventures
  post    '/adventures/search',     to: 'adventures#search'

  # Matches
  get     '/matches',               to: 'matches#index'
  post    '/matches/reject',        to: 'matches#reject'
  post    '/matches/accept',        to: 'matches#accept'

  # Chats
  resources :chats do
    post '/', to: 'chats#new_message'
    post '/retrieve', to: 'chats#retrieve'
  end
end

app/models/chat.rb
# frozen_string_literal: true

class Chat < ApplicationRecord
  has_many :messages
  has_many :users, through: :messages
end

app/controllers/chats_controller.rb
# frozen_string_literal: true

class ChatsController < ApplicationController
  before_action :auth_user!
  skip_before_action :verify_authenticity_token, only: %i[retrieve new_message]
  def index
    @current_user.profile.update(new_matches: false)
    @chats = @current_user.chats.order(updated_at: :desc)
  end

  def show
    @chat = Chat.find params[:id]
  end

  def retrieve
    chat = Chat.find params[:chat_id]
    render json: { html: render_to_string(partial: 'chat', locals: { chat: }) }
  end

  def new_message
    chat = Chat.find params[:chat_id]
    chat.messages.create!(message_params.merge(user_id: @current_user.id))
    render json: { html: render_to_string(partial: 'chat', locals: { chat: }) }
  end

  def destroy
    chat = Chat.find params[:id]
    u = chat.users.find_by('users.id != ?', @current_user.id).profile
    @current_user.profile.rejects << u.id
    @current_user.profile.save
    chat.destroy
    redirect_to chats_path, alert: 'You have unmatched.'
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/views/chats/_chat.html.erb
<% match = chat.users.find_by('users.id != ?', @current_user.id).profile %>
<% if match.photo.present? %>
  <%= image_tag match.photo.variant(resize_to_limit: [100, 100]), class: "rounded mx-auto" %>
<% else %>
  <i class="fa fa-user fa-2xl d-flex align-items-center justify-content-center mx-auto rounded col-2" style="width: 100px; height: 100px; background: whitesmoke;"></i>
<% end %>
<div class="container messages d-flex flex-column-reverse py-4 mt-4" style="max-height: 600px;">
  <% chat.messages.order(created_at: :desc).each do |msg| %>
    <% slf = msg.user == @current_user %>
    <% next if msg.body.blank? %>
    <div class="row border rounded my-3 px-2 py-1 w-75 <%= slf ? "align-self-end bg-primary-subtle" : "bg-light" %>">
      <%= content_tag :strong, msg.user.name, class: "col-12 #{" text-end" if slf}" %>
      <%= content_tag :span, msg.body, class: ("text-end" if slf) %>
    </div>
    <sub class="w-25 sub <%= "text-end align-self-end" if slf %>">
      <%= msg.created_at.strftime("%b %e, %l:%M %p") %>
    </sub>
  <% end %>
</div>
<hr>

app/views/chats/index.html.erb
<div class="container-fluid">
<% if @chats.blank? %>
  <div class="text-center mb-2">No matches found.</div>
  <%= link_to "Start matching", matches_path, class: "btn btn-soft d-block" %>
<% end %>
<% @chats.each do |chat| %>
  <% match = chat.users.find_by('users.id != ?', @current_user.id).profile %>
  <%= link_to chat_path(chat), class: "text-decoration-none text-black" do %>
    <div class="row">
      <% if match.photo.present? %>
        <%= image_tag match.photo.variant(resize_to_limit: [100, 100]), class: "rounded col-3" %>
      <% else %>
        <i class="fa fa-user fa-2xl d-flex align-items-center justify-content-center mx-auto rounded col-2" style="width: 100px; height: 100px; background: whitesmoke;"></i>
      <% end %>
      <div class="col-9 d-flex justify-content-center flex-column">
        <%= content_tag :h4, match.name %>
        <% last_msg = chat.messages.last %>
        <%= content_tag :p, class: "#{last_msg.user == @current_user ? "bg-primary-subtle" : "bg-light"} rounded text-black border py-2 px-3 me-4" do %>
          <%= last_msg.body %>
          <br>
          <%= content_tag :sub, chat.messages.last.created_at.strftime("%b %e, %l:%M %p"), class: "float-end mb-2" %>
        <% end %>
      </div>
    </div>
  <% end %>
  <%= button_to "Unmatch",
                "/chats/#{chat.id}",
                method: :delete, data: { confirm: "Are you sure?" }, class: "btn text-danger btn-sm ms-2" %>
  <hr>
<% end %>
</div>

app/views/chats/show.html.erb
<style>
  .messages { max-height: 800px; overflow: auto; }
</style>

<div data-controller="chat" class="container-fluid my-3 pb-3">
  <div data-chat-target="chat" id="chat" data-id="<%= @chat.id %>">
    <%= render partial: "chat", locals: { chat: @chat } %>
  </div>
  <div class="text-end">
      <%= text_area_tag :body, "",
                        required: true,
                        rows: 2,
                        columns: 40,
                        data: { "chat-target": "input" },
                        style: "resize: none;",
                        class: "form-control form-control-sm py-1" %>
      <%= button_tag "Send",
                      type: "button",
                      data: { action: "click->chat#sendMessage", id: @chat.id },
                      class: "btn btn-soft btn-sm mt-2 px-3" %>
  </div>
</div>